/// Les icônes et la nature des catégories de départ.
///
/// Les icônes sont des noms Material Symbols, les mêmes que le sélecteur
/// d'icônes propose : une catégorie créée à la main et une catégorie de
/// départ se rangent pareil en base.
library;

/// Le nom court de `categories.json` vers l'icône Material.
const iconeDeCategorie = <String, String>{
  'courses': 'shopping_cart',
  'sorties': 'restaurant',
  'logement': 'home',
  'transports': 'directions_car',
  'abonnements': 'autorenew',
  'shopping': 'shopping_bag',
  'sante': 'medical_services',
  'beaute': 'spa',
  'loisirs': 'attractions',
  'etudes': 'school',
  'volant': 'badge',
  'enfant': 'child_care',
  'pro': 'business_center',
  'cadeau': 'card_giftcard',
  'animaux': 'pets',
  'banque': 'account_balance',
  'impots': 'gavel',
  'retrait': 'local_atm',
  'aclasser': 'help',
  'salaire': 'payments',
  'revenus': 'trending_up',
  'epargne': 'savings',
  'interne': 'sync_alt',
};

/// Les sous-catégories qui ont une icône à elles. Les autres reprennent
/// celle de leur catégorie.
const iconeDeSous = <String, String>{
  'Supermarché': 'local_grocery_store',
  'Boulangerie': 'bakery_dining',
  'Marché et primeur': 'nutrition',
  'Drive et livraison': 'delivery_dining',
  'Cave et alcool': 'wine_bar',
  'Restaurant': 'restaurant',
  'Fast-food': 'fastfood',
  'Bar et café': 'local_cafe',
  'Bars et clubs': 'nightlife',
  'Livraison de repas': 'delivery_dining',
  'Cantine et resto U': 'lunch_dining',
  'Loyer': 'key',
  'Électricité': 'bolt',
  'Gaz': 'local_fire_department',
  'Eau': 'water_drop',
  'Assurance habitation': 'shield',
  'Entretien et bricolage': 'handyman',
  'Décoration': 'palette',
  'Mobilier': 'chair',
  'Électroménager': 'kitchen',
  'Extérieur et jardin': 'yard',
  'Carburant': 'local_gas_station',
  'Péage': 'toll',
  'Parking': 'local_parking',
  'Transports en commun': 'directions_bus',
  'Train': 'train',
  'Avion': 'flight',
  'Taxi et VTC': 'local_taxi',
  'Entretien et réparation': 'car_repair',
  'Assurance auto': 'shield',
  'Location de véhicule': 'car_rental',
  'Vélo et trottinette': 'pedal_bike',
  'Streaming vidéo': 'live_tv',
  'Musique': 'music_note',
  'Forfait mobile': 'smartphone',
  'Téléphonie fixe': 'call',
  'Internet': 'wifi',
  'Câble et satellite': 'satellite_alt',
  'Cloud et logiciels': 'cloud',
  'Licences': 'qr_code_2',
  'Presse et livres audio': 'headphones',
  'Salle de sport': 'fitness_center',
  'Jeux vidéo en ligne': 'sports_esports',
  'Vêtements': 'checkroom',
  'Chaussures': 'steps',
  'Vêtements de sport': 'sprint',
  'Articles de sport': 'sports_soccer',
  'High-tech': 'devices',
  'Accessoires et bijoux': 'diamond',
  'Beauté et parfum': 'spa',
  'Maison et déco': 'weekend',
  'Livres': 'menu_book',
  'Films et séries': 'movie',
  'Jeux vidéo et jouets': 'toys',
  'Cadeaux': 'redeem',
  'Marketplace': 'package_2',
  'Seconde main': 'recycling',
  'Médecin': 'stethoscope',
  'Pharmacie': 'medication',
  'Dentiste': 'dentistry',
  'Opticien et ophtalmo': 'eyeglasses',
  'Mutuelle': 'health_and_safety',
  'Psy et bien-être': 'psychology',
  'Coiffeur et barbier': 'content_cut',
  'Spa et massage': 'spa',
  'Sport et activités': 'sports_tennis',
  "Sports d'hiver": 'downhill_skiing',
  'Voyages et vacances': 'luggage',
  'Hôtels et hébergement': 'hotel',
  'Sorties culturelles': 'museum',
  'Cinéma et concerts': 'movie',
  'Divertissements': 'sports_esports',
  'Hobbies': 'palette',
  'Jeux et paris': 'casino',
  'Photo et vidéo': 'photo_camera',
  'Frais de scolarité': 'school',
  'Matériel informatique': 'laptop',
  'Logement étudiant': 'apartment',
  'Prêt étudiant': 'account_balance',
  'Permis voiture': 'directions_car',
  'Permis moto': 'two_wheeler',
  'Permis bateau': 'sailing',
  'Permis poids lourd': 'local_shipping',
  'Code de la route': 'traffic',
  'Heures de conduite': 'schedule',
  'Examens': 'task_alt',
  'Frais de dossier': 'description',
  'Baby-sitter et crèche': 'child_care',
  'École': 'school',
  'Jouets': 'toys',
  'Frais bancaires': 'account_balance',
  'Incidents de paiement': 'report',
  'Cotisation carte': 'credit_card',
  'Débit mensuel carte': 'credit_card',
  'Agios': 'percent',
  'Remboursement de prêt': 'real_estate_agent',
  'Prêt immobilier': 'house',
  'Impôt sur le revenu': 'receipt_long',
  'Taxe foncière': 'house',
  "Taxe d'habitation": 'home',
  'TVA': 'percent',
  'Amendes': 'local_police',
  "Retraits d'espèces": 'local_atm',
  'Chèques émis': 'edit_note',
  'Virements à des proches': 'volunteer_activism',
  'Salaire': 'payments',
  'Alternance': 'work',
  'Primes': 'workspace_premium',
  'Remboursements': 'currency_exchange',
  'Virements reçus': 'call_received',
  'Ventes (Vinted, Leboncoin)': 'sell',
  'Aides et CAF': 'family_restroom',
  'Intérêts': 'trending_up',
  'Livret A': 'savings',
  'Livret jeune': 'savings',
  "Vers l'épargne": 'south',
  "Depuis l'épargne": 'north',
  'Entre mes comptes courants': 'sync_alt',
  'Autres': 'more_horiz',
};

/// Les catégories dont les dépenses sont par défaut essentielles. Les
/// autres sont du plaisir ; chaque opération peut changer d'avis.
const naturesEssentielles = {
  'Courses', 'Logement', 'Transports', 'Santé', 'Études', 'Permis', 'Enfants',
  'Dépenses pro', 'Animaux', 'Banque et frais', 'Impôts et taxes',
};

/// Des sous-catégories essentielles dans une catégorie qui ne l'est pas.
const sousEssentielles = {'Forfait mobile', 'Internet', 'Téléphonie fixe', 'Mutuelle'};
